class STRINGS:

    if_login = 'foo'
    reset_perm_script = '/Users/talkerbis/Documents/Android_scripts/ninstall.txt'
    phone_for_login = 'mobi.nexar.dashcam:id/signInPhone'
    MESSAGES_ELEMENT_NOTIFICATIONS = 'android:id/message_text'
    PIN_CODE_UI = 'mobi.nexar.dashcam:id/pinCode'
    TOP_MENU_ACC_ID = 'Navigate up'
    IN_MESSAGE_MENU_ACC_ID = 'More options'
    POLICY_OWNER_PHONE_NUMBER_X_PATH = '//*[@id="container"]/div/div/main/div[2]/div/div[1]/input'


class BUTTONS:
    ACTION = 'mobi.nexar.dashcam:id/actionBtn'
    ALLOW = 'com.android.packageinstaller:id/permission_allow_button'
    name_for_login = 'mobi.nexar.dashcam:id/signInName'
    SIGN_UP_BUTTON = 'mobi.nexar.dashcam:id/btnPhoneLogin'
    re_send_otp = 'mobi.nexar.dashcam:id/linkResendCode'
    message_text = 'com.google.android.apps.messaging:id/message_text'
    CLAL_GOT_IT = 'mobi.nexar.dashcam:id/button_insurance_summary'
    TOP_LEFT_MENU = '//android.widget.ImageButton[@content-desc="Navigate up"]'
    RESEND_OTP = 'mobi.nexar.dashcam:id/linkResendCode'
    LOGIN_BUTTON = 'mobi.nexar.dashcam:id/btnPhoneLogin'
    AGREE_TOS = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.LinearLayout'
    DELETE_MESSAGE_POPUP = 'android:id/button1'
    SEND_SMS_ICON = 'com.google.android.apps.messaging:id/send_message_button_container'
    SMS_TOP_TITLE = 'com.google.android.apps.messaging:id/conversation_title_container'

class CH_XPATH:
    POLICY_NUMBER = '//*[@id="container"]/div/div/main/div[2]/div/div[1]/input'
    POLICY_NAME = '//*[@id="container"]/div/div/main/div[2]/div/div[2]/input'
    HOUSE_NUMBER = '//*[@id="container"]/div/div/main/div[2]/div/div[3]/input'
    STREET = '//*[@id="container"]/div/div/main/div[2]/div/div[4]/input'
    CITY = '//*[@id="container"]/div/div/main/div[2]/div/div[5]/input'
    CREATE_POLICY_BUTTON = '//*[@id="container"]/div/div/main/div[2]/div/button'
    DONE_AFTER_POLICY_SENT = '//*[@id="container"]/div/div/main/div[2]/div/div[1]/button'
    EXCEPTED_DRIVERS_LIST = '//*[@id="container"]/div/div/main/div[2]/div/div[6]/div'
    ONE_EXCEPTED_DRIVER = '//*[@id="container"]/div/div/main/div[2]/div/div[6]/div/div[2]/div[1]'
    LOG_IN_WITH_GOOGLE = '//*[@id="container"]/div/div/main/div[2]/button[1]'
    MAIL_FIELD = '//*[@id="identifierId"]'
    NEXT_BUTTON = '//*[@id="identifierNext"]/content/span'
    PASSWORD_GOOGLE = '//*[@id="password"]/div[1]/div/div[1]/input'
    PASSWORD_NEXT_BUTTON = '//*[@id="passwordNext"]/content/span'
    DASHBOARD_VIEW_ALL_BUTTON = '//*[@id="container"]/div/div/main/div[2]/div[2]/div[2]/div[3]'
    DASHBOARD_CREATE_POLICY_BUTTON = '//*[@id="container"]/div/div/main/div[1]/button[2]'